### ISSUE TITLE
BLANK STATE

### ISSUE THREAD

**Issue by alxngyn** [cs361-W16/Group18-2#1]
BLANK STATE
https://github.com/cs361-W16/Group18-2/wiki/Target-Framework,-Layout,-and-User
- Should have a huge title "AcesUp" at the top
- should have a large button in the center representing the "START" button
- probably should have a list of our names somewhere on the bottom
- everything else is hidden

**Comment by siebertc** [comment]
I'll take this one.

**Comment by siebertc** [comment]
Button added and CSS changes to Blank State
